# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://kiskander.github.io/cisco-learning-codelabs/"

title = "Learning@Cisco Launchpad 🚀"
languageCode = "en-us"
theme = "codelabs"

[params]
homeTitle = "Welcome to the Launchpad"
homeDescription = """Launch your learning with a curated list of learning content and watch your skills skyrocket to the moon"""
footer = "<a href=\"https://www.cisco.com\">Cisco Learning and Certification</a>"
feedbackLink = "mailto:donotreply@cisco.com"
[params.categoryColors]
mlops = "#1A73E8"
tfx = "#f58442"
gcp = "#3884ff"
jupyter = "#fc4903"
mtest = "#1A73E8"
