name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build hugo
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: |
          ./build_docs.sh
          run: echo "This step will always run"

      - name: Git init
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'

      - name: Git add
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: git add --force .

      - name: Git commit
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: git commit -m "publish"

      - name: Push public to branch
        if: ${{ steps.filter.outputs.docs == 'true' }}
        run: |
          git push -f origin main
